

DECLARE @COD_PROD INT
DECLARE @NCM INT
DECLARE @DESC NVARCHAR(MAX)
DECLARE @DUP INT

DECLARE DUPLICADO CURSOR FOR
SELECT COD_PRODUTO,NCM,DESCRICAO,COUNT(*) AS DUP FROM R75 GROUP BY COD_PRODUTO,NCM,DESCRICAO HAVING COUNT(*) > 1

OPEN DUPLICADO

FETCH NEXT FROM DUPLICADO INTO @COD_PROD,@NCM,@DESC,@DUP

WHILE @@FETCH_STATUS = 0
BEGIN
 SELECT TOP(@DUP - 1) * FROM R75 WHERE COD_PRODUTO = @COD_PROD
 FETCH NEXT FROM DUPLICADO INTO @COD_PROD,@NCM,@DESC,@DUP
END

CLOSE DUPLICADO
DEALLOCATE  DUPLICADO
